---
- name: win_ping module demo
  hosts: windows
  become: false
  gather_facts: false
  
  tasks:
    - name: Example from an Ansible Playbook
      win_ping:

    - name: Induce an exception to see what happens
      win_ping:
        data: crash
