---
- name: unarchive module demo
  hosts: localhost
  become: false
  vars:
    myurl: "https://github.com/lucab85/ansible-pilot/archive/refs/heads/master.zip"
  tasks:
    - name: extractor presents
      ansible.builtin.yum:
        name:
          - unzip
          - tar
        state: present
      become: true
    # - name: download file from url
    #   ansible.builtin.get_url:
    #     url: "{{ myurl }}"
    #     dest: "/home/pm1990/Ansiblepilot/Ansiblepilot"
    - name: extract archive
      ansible.builtin.unarchive:
        src: "{{ myurl }}"
        dest: "/home/pm1990/Ansiblepilot/Ansiblepilot/"
        remote_src: true
        validate_certs: true