---
- name: user module demo
  hosts: centos
  become: true
  tasks:
    - name: user example not present
      ansible.builtin.user:
        name: example
        state: "absent"
        remove: true