---
- name: user module demo
  hosts: centos
  become: true
  vars:
    myuser: "example"
    mygroups:
      - adm
      - sys
  tasks:
    - name: adding secondary group(s)
      ansible.builtin.user:
        name: "{{ myuser }}"
        groups: "{{ mygroups }}"
        append: true