---
- name: copy module demo
  hosts: centos
  become: false
  tasks:
    - name: copy multiple file(s)
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/home/devops/"
        owner: root
        mode: '0644'
      with_fileglob:
        - "templates/*.j2"