---
- name: yum module demo
  hosts: all
  become: true
  tasks:
    - name: install package yum
      yum:
        name: wget
        state: present
    - name: install package apt
      apt:
        name: wget
        state: present
    # - name: install package dnf
    #   dnf:
    #     name: wget
    #     state: present
    - name: install package
      apt:
        name: curl
        state: present