---
- name: group module demo
  hosts: dwt-ubuntu4
  become: true
  vars:
    myuser: "test1"
    mypassword: "password"
  tasks:
    - name: root test
      ansible.builtin.debug:
        msg: "privilage escalation sucessfull"
    - name: user example present
      ansible.builtin.user:
        name: "{{ myuser }}"
        password: "{{ 'password' | password_hash('sha512', 'mysecretsalt') }}"
        groups:
          - sudo
        state: "present"
        shell: "/bin/bash"
        system: false
        create_home: true
        home: "/home/example"
        comment: "Ansible example"
        generate_ssh_key: true
    - name: password expiration
      ansible.builtin.user:
        name: "{{ myuser }}"
        password_expire_min: 7
        password_expire_max: 90
        
# ansible-playbook -i inventory debug_missing_sudo.yml -bK <- to manually ask for password promtp to become root